### ISSUE TITLE
PackageNotFound ctypes

### ISSUE THREAD

**Issue by termithorbor** [MarkusHaak/crossalign#2]
Hi Markus,

ich bekomme leider immer den folgenden Fehler, wenn ich das Conda Environment anlegen möchte: 

Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - ctypes

Hab schon Python in Conda neu installiert, aber das hat leider auch nicht geholfen.
Hast du eine Ahnung was ich noch machen könnte?
Danke schon mal.

Liebe Grüße,
Thorben

**Comment by termithorbor** [comment]
Habe jetzt einfach ctypes aus der environment.yml Datei gelöscht, weil es in der Vorgängerversion auch nicht war und auch kein Conda Package sondern ein Python Tool ist. Jetzt funktioniert die Erstellung des Environments ohne Probleme :)

**Comment by MarkusHaak** [comment]
Hi Thorben,
entschuldige meine verspätete Antwort. Damit hast du alles richtig gemacht, ctypes war fälschlicherweise in den dependencies.
Liebe Grüße
Markus
